"""empty message

Revision ID: 11f48346c4de
Revises: 8b60dfb8122c
Create Date: 2017-01-25 21:02:17.576652

"""

# revision identifiers, used by Alembic.
revision = '11f48346c4de'
down_revision = '8b60dfb8122c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report_urls', sa.Column('report_title', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('report_urls', 'report_title')
    ### end Alembic commands ###
