"""empty message

Revision ID: 470c51636b02
Revises: a32da8a7ebc5
Create Date: 2016-07-29 16:33:35.187076

"""

# revision identifiers, used by Alembic.
revision = '470c51636b02'
down_revision = 'a32da8a7ebc5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activity_logs', 'event_costs')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity_logs', sa.Column('event_costs', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    ### end Alembic commands ###
