"""empty message

Revision ID: 5930610ecee9
Revises: fb4b52ea61a3
Create Date: 2016-09-23 15:24:01.406385

"""

# revision identifiers, used by Alembic.
revision = '5930610ecee9'
down_revision = 'fb4b52ea61a3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery_method',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column(u'activity_logs', sa.Column('delivery_method_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'activity_logs', 'delivery_method', ['delivery_method_id'], ['id'])
    op.add_column(u'expense_sheets', sa.Column('delivery_method_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'expense_sheets', 'delivery_method', ['delivery_method_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'expense_sheets', type_='foreignkey')
    op.drop_column(u'expense_sheets', 'delivery_method_id')
    op.drop_constraint(None, 'activity_logs', type_='foreignkey')
    op.drop_column(u'activity_logs', 'delivery_method_id')
    op.drop_table('delivery_method')
    ### end Alembic commands ###
