"""empty message

Revision ID: 6aaae13c483c
Revises: aa3499b09be2
Create Date: 2016-09-23 15:26:13.039992

"""

# revision identifiers, used by Alembic.
revision = '6aaae13c483c'
down_revision = 'aa3499b09be2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_day',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('work_day')
    ### end Alembic commands ###
