"""empty message

Revision ID: 7d7ac7f640f0
Revises: 23acf8bca9b0
Create Date: 2016-05-03 11:32:37.593963

"""

# revision identifiers, used by Alembic.
revision = '7d7ac7f640f0'
down_revision = '23acf8bca9b0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('districts', sa.Column('name', sa.String(length=255), nullable=False))
    op.create_unique_constraint(None, 'districts', ['name'])
    op.add_column('schools', sa.Column('district_id', sa.Integer(), nullable=True))
    op.add_column('schools', sa.Column('name', sa.String(length=255), nullable=False))
    op.create_unique_constraint(None, 'schools', ['name'])
    op.create_foreign_key(None, 'schools', 'districts', ['district_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'schools', type_='foreignkey')
    op.drop_constraint(None, 'schools', type_='unique')
    op.drop_column('schools', 'name')
    op.drop_column('schools', 'district_id')
    op.drop_constraint(None, 'districts', type_='unique')
    op.drop_column('districts', 'name')
    ### end Alembic commands ###
