"""empty message

Revision ID: 7ea398cc6e3a
Revises: 2f38d292dc6d
Create Date: 2016-07-22 15:04:36.177142

"""

# revision identifiers, used by Alembic.
revision = '7ea398cc6e3a'
down_revision = '2f38d292dc6d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('cell_reimbursement', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'cell_reimbursement')
    ### end Alembic commands ###
