"""empty message

Revision ID: a32da8a7ebc5
Revises: 7ea398cc6e3a
Create Date: 2016-07-28 15:41:08.178463

"""

# revision identifiers, used by Alembic.
revision = 'a32da8a7ebc5'
down_revision = '7ea398cc6e3a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expense_sheets', sa.Column('expense_sheet_end', sa.DateTime(), nullable=True))
    op.add_column('expense_sheets', sa.Column('expense_sheet_start', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expense_sheets', 'expense_sheet_start')
    op.drop_column('expense_sheets', 'expense_sheet_end')
    ### end Alembic commands ###
