"""empty message

Revision ID: aa3499b09be2
Revises: 5930610ecee9
Create Date: 2016-09-23 15:25:02.732684

"""

# revision identifiers, used by Alembic.
revision = 'aa3499b09be2'
down_revision = '5930610ecee9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('school_designation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column(u'activity_logs', sa.Column('school_designation_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'activity_logs', 'school_designation', ['school_designation_id'], ['id'])
    op.add_column(u'expense_sheets', sa.Column('school_designation_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'expense_sheets', 'school_designation', ['school_designation_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'expense_sheets', type_='foreignkey')
    op.drop_column(u'expense_sheets', 'school_designation_id')
    op.drop_constraint(None, 'activity_logs', type_='foreignkey')
    op.drop_column(u'activity_logs', 'school_designation_id')
    op.drop_table('school_designation')
    ### end Alembic commands ###
