"""empty message

Revision ID: f4e03e1429e3
Revises: 6aaae13c483c
Create Date: 2016-09-28 11:21:44.510027

"""

# revision identifiers, used by Alembic.
revision = 'f4e03e1429e3'
down_revision = '6aaae13c483c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity_logs', sa.Column('activity_hours', sa.Integer(), nullable=True))
    op.add_column('activity_logs', sa.Column('num_hours_planning', sa.Integer(), nullable=True))
    op.add_column('activity_logs', sa.Column('planner_name', sa.String(length=255), nullable=True))
    op.add_column('activity_logs', sa.Column('total_num_participants', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activity_logs', 'total_num_participants')
    op.drop_column('activity_logs', 'planner_name')
    op.drop_column('activity_logs', 'num_hours_planning')
    op.drop_column('activity_logs', 'activity_hours')
    ### end Alembic commands ###
