"""empty message

Revision ID: fb4b52ea61a3
Revises: a6a1d055acbe
Create Date: 2016-09-23 15:21:22.605629

"""

# revision identifiers, used by Alembic.
revision = 'fb4b52ea61a3'
down_revision = 'a6a1d055acbe'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_scope',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('activity_topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('activity_topic_identifier_al',
    sa.Column('activity_topic_id', sa.Integer(), nullable=True),
    sa.Column('activity_log_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['activity_log_id'], ['activity_logs.id'], ),
    sa.ForeignKeyConstraint(['activity_topic_id'], ['activity_topics.id'], )
    )
    op.create_table('activity_topic_identifier_es',
    sa.Column('activity_topic_id', sa.Integer(), nullable=True),
    sa.Column('expense_sheet_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['activity_topic_id'], ['activity_topics.id'], ),
    sa.ForeignKeyConstraint(['expense_sheet_id'], ['expense_sheets.id'], )
    )
    op.add_column(u'activity_logs', sa.Column('activity_scope_id', sa.Integer(), nullable=True))
    op.add_column(u'activity_logs', sa.Column('location', sa.String(length=255), nullable=True))
    op.create_foreign_key(None, 'activity_logs', 'activity_scope', ['activity_scope_id'], ['id'])
    op.drop_column(u'activity_logs', 'activity_hours')
    op.add_column(u'expense_sheets', sa.Column('activity_scope_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'expense_sheets', 'activity_scope', ['activity_scope_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'expense_sheets', type_='foreignkey')
    op.drop_column(u'expense_sheets', 'activity_scope_id')
    op.add_column(u'activity_logs', sa.Column('activity_hours', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'activity_logs', type_='foreignkey')
    op.drop_column(u'activity_logs', 'location')
    op.drop_column(u'activity_logs', 'activity_scope_id')
    op.drop_table('activity_topic_identifier_es')
    op.drop_table('activity_topic_identifier_al')
    op.drop_table('activity_topics')
    op.drop_table('activity_scope')
    ### end Alembic commands ###
